[scripts] Fix agents for sc-machine 0.9.0
ostis-ai/scp-machine pull request #12
Opened 2024-03-07 17:02 UTC by NikitaZotov

2024-03-08 15:07 UTC, MksmOrlov requested changes
No tests - no review

2024-03-08 15:07 UTC, MksmOrlov commented on scp/string_operators/SCPOperatorStringToUpperCase.cpp
> +            ScAddr answerLink =m_memoryCtx.CreateLink();
```suggestion
            ScAddr answerLink = m_memoryCtx.CreateLink();
```
use auto formatter

2024-03-11 13:33 UTC, MksmOrlov approved these changes

2024-03-12 18:17 UTC, ShunkevichDV approved these changes

2024-03-16 09:46 UTC, merged